export class ContractModel {
   ContractId: string;
   ContractCode: string;
   CustomerId: string;
   Value: number;
   ExpContract: number;
   SignContractDt: Date;
   ChargeDt: Date;
   MonthCharge: number;
   Status: string;
   Notes: string;
   RecordStatus: string;
   MakerId: string;
   DepId: string;
   CreateDt: Date;
   AuthStatus: string;
   CheckerId: string;
   ApproveDt: Date;
   EditorId: string;
   EditDt: Date;
   XmlTemp: string;
   DataTemp: string;
   DebitBalance: number;
   PaidAmt: number;
   DepositAccountBeforLd: number;
   OptimalAmt: number;
   SeoAmt: number;
   DebitMaintainFee: number;
   DepositAccount: number;
   DepositLiquidation: number;
   IsFirstFee: boolean;
   IsLandingPage: boolean;
   TypeGoogle: string;
  CONTRACT_TYPE : string;
   CustomerCode: string;
   CustomerName: string;
  constructor() {
    this.ContractId = '';
    this.ContractCode = '';
    this.CustomerId = '';
    this.Value = 0;
    this.ExpContract = 0;
    this.SignContractDt = new Date();
    this.ChargeDt = new Date();
    this.MonthCharge = 0;
    this.Status = '';
    this.Notes = '';
    this.RecordStatus = '';
    this.MakerId = '';
    this.DepId = '';
    this.CreateDt = new Date();
    this.AuthStatus = '';
    this.CheckerId = '';
    this.ApproveDt = new Date();
    this.EditorId = '';
    this.EditDt = new Date();
    this.XmlTemp = '';
    this.DataTemp = '';
    this.DebitBalance =0;
    this.PaidAmt = 0;
    this.DepositAccountBeforLd = 0;
    this.OptimalAmt = 0;
    this.SeoAmt = 0;
    this.DebitMaintainFee = 0;
    this.DepositAccount = 0;
    this.DepositLiquidation = 0;
    this.IsFirstFee = false;
    this.IsLandingPage = false;
    this.TypeGoogle = '';
    this.CustomerCode = '';
    this.CustomerName = '';
    this.CONTRACT_TYPE = '';

  }
}
